version: '3.8'

services:
  keydb:
    image: eqalpha/keydb
    container_name: keydb
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - redis-network

  upstash-proxy:
    image: hiett/serverless-redis-http:latest
    container_name: upstash-proxy
    ports:
      - "${UPSTASH_PROXY_PORT:-8000}:8000"
    environment:
      SRH_MODE: env
      SRH_TOKEN: ${UPSTASH_TOKEN}
      SRH_CONNECTION_STRING: 'redis://redis:6379'
      SRH_PORT: ${UPSTASH_PROXY_PORT:-8000}
    depends_on:
      keydb:
        condition: service_healthy
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
